Controllers/LoginRegController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using beltexam.Models;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using System.Data.Entity;

namespace beltexam.Controllers
{
  public class LoginRegController : Controller
  {
    private beltexamContext dbContext;
    
    public LoginRegController(beltexamContext context)
    {
      dbContext = context;
    
    }
    
    [HttpGet]
    [Route("")]
    public IActionResult Index()
    {
      return View();
    }

    [HttpPost("RegisterUser")]
    public IActionResult RegisterUser(User user)
    {
      if (ModelState.IsValid)
      {
        if (dbContext.Users.Any(u => u.Email == user.Email))
        {
          ModelState.AddModelError("Email", "Email already in use!");
          return View("Index");
        }
        else
        {
          PasswordHasher<User> Hasher = new PasswordHasher<User>();
          user.Password = Hasher.HashPassword(user, user.Password);

          dbContext.Add(user);
          dbContext.SaveChanges();
          var AddedUser = dbContext.Users.FirstOrDefault(u => u.Email == user.Email);
          HttpContext.Session.SetInt32("UserId", AddedUser.UserId);
          int? LoggedInUserId = HttpContext.Session.GetInt32("UserId");

          return RedirectToAction("ShowHome", "UserAndActivity");
        }
      }
      else
      {
        return View("Index");
      }
    }

    [HttpGet("ViewLoginUser")]
    public IActionResult ViewLoginUser()
    {
      return View();
    }

    [HttpPost("LoginUser")]
    public IActionResult LoginUser(LoginUser UserSubmission)
    {
      if (ModelState.IsValid)
      {
        var UserToCheck = dbContext.Users.FirstOrDefault(u => u.Email == UserSubmission.Email);
        if (UserToCheck == null)
        {
          ModelState.AddModelError("Email", "Invalid Email or Password");
          return View("Index");
        }
        var hasher = new PasswordHasher<LoginUser>();

        var result = hasher.VerifyHashedPassword(UserSubmission, UserToCheck.Password, UserSubmission.Password);

        if (result == 0)
        {
          ModelState.AddModelError("Password", "Invalid Email or Password");
          return View("Index");
        }
        HttpContext.Session.SetInt32("UserId", UserToCheck.UserId);
        int? LoggedInUserId = HttpContext.Session.GetInt32("UserId");
        return RedirectToAction("ShowHome", "UserAndActivity");
      }
      return View("Index");
    }

    [HttpGet("logout")]
    public IActionResult Logout()
    {
      HttpContext.Session.Clear();
      return View("Index");
    }
  }


}


Views/Shared/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@Html.Partial("_Login")
@Html.Partial("_Register")

Views/Shared/_HeaderWithHome.cshtml
<h1>Dojo Activity Center</h1>
<a href="/home">Home</a>
<a class="logout" href="/logout">Logout</a>
<hr>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - beltexam</title>
    
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.css"
            asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
        
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery">
        </script>
        
        
        <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Login.cshtml
@using beltexam.Models
@model LoginUser

<h1 class="LoginHeader">Login to the Activity Planner!</h1>
<a class="login" href="/">Register</a>

<form asp-action="LoginUser" asp-controller="LoginReg" method="post">
  <label for="Email">Email</label>
  <input asp-for="Email">
  <span asp-validation-for="Email"></span>

  <label for="Password">Password</label>
  <input asp-for="Password">
  <span asp-validation-for="Password"></span>

  <input type="submit" class="btn btn-primary" value="Sign In Now">
</form>

Views/Shared/_Register.cshtml
@using beltexam.Models
@model User

<h1 class="LoginHeader">Register to the Activity Planner!</h1>
<a class="login" href="/ViewLoginUser">Login</a>
<div class = "form-container">
  <div class="left-login">
    <form class="form" method="post" asp-action="RegisterUser" asp-controller="LoginReg">
      <label asp-for="FirstName">First Name</label>
      <input asp-for="FirstName">
      <span asp-validation-for="FirstName"></span>

      <label asp-for="LastName">Last Name</label>
      <input asp-for="LastName">
      <span asp-validation-for="LastName"></span>

      <label asp-for="Email">Email Name</label>
      <input asp-for="Email">
      <span asp-validation-for="Email"></span>
      <input type="submit" value="Sign Up Now" class="btn btn-primary submit">
    </div>
  <div class="right-login">
      <label asp-for="Password">Password</label>
      <input asp-for="Password">
      <span asp-validation-for="Password"></span>

      <label asp-for="Confirm">Confirm</label>
      <input asp-for="Confirm">
    <span asp-validation-for="Confirm"></span>
  </form>
  </div>
</div>