Models/Activity.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;
using System.Collections.Generic;

namespace beltexam.Models
{
  public class Activity
  {
    [Key]
    public int ActivityId { get; set; }
    [Required]
    [MinLength(2)]
    public string Title {get;set;}
    [Required]
    public DateTime Date {get;set;}
    [Required]
    [MinLength(10)]
    public string Description { get; set; }
    public int CreatorId {get;set;}
    public string CreatorName {get;set;}
    [Required]
    public int Duration {get;set;}
    public string DurationUnit {get;set;}
    public List<UserAndActivity> UserAndActivities {get;set;}
    
  }
}

Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using beltexam.Models;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace beltexam.Controllers
{
  public class ActivityController : Controller
  {
    private beltexamContext dbContext;

    public ActivityController(beltexamContext context)
    {
      dbContext = context;

    }
    [HttpGet("showcreateactivity")]
    public IActionResult ShowCreateActivity()
    {
      if (HttpContext.Session.GetInt32("UserId") == null)
      {
        return View("Index");
      }
      int? LoggedInUserId = HttpContext.Session.GetInt32("UserId");
      ViewBag.LoggedInUserId = LoggedInUserId;
      var LoggedInUser = dbContext.Users.FirstOrDefault(u => u.UserId == LoggedInUserId);
      ViewBag.LoggedInUser = LoggedInUser;

      return View();
    }

    [HttpPost("CreateActivity")]
    public IActionResult CreateActivity(Activity NewActivity, double Hour, double Minute, string ampm, string FirstName, string LastName)
    {

      if(ModelState.IsValid)
      {
        NewActivity.CreatorName = FirstName + " " + LastName;
        
        if (ampm == "am")
        {
          Hour += 12;
        }
        NewActivity.Date = NewActivity.Date.AddHours(Hour).AddMinutes(Minute);
        if (NewActivity.Date < DateTime.Now)
        {
          ModelState.AddModelError("Date", "Date Must be after today");
          return View("ShowCreateActivity");
        }
        dbContext.Add(NewActivity);
        dbContext.SaveChanges();
        return RedirectToAction("ShowHome", "UserAndActivity");

      }
      int? LoggedInUserId = HttpContext.Session.GetInt32("UserId");
      ViewBag.LoggedInUserId = LoggedInUserId;
      var LoggedInUser = dbContext.Users.FirstOrDefault(u => u.UserId == LoggedInUserId);
      ViewBag.LoggedInUser = LoggedInUser;
      
      
      return View("ShowCreateActivity");
    }

    [HttpGet("deleteactivity/{id}")]
    public IActionResult DeleteActivity(int id)
    {
      var ActivityToDelete = dbContext.Activities.FirstOrDefault(a => a.ActivityId == id);
      dbContext.Remove(ActivityToDelete);
      dbContext.SaveChanges();
      return RedirectToAction("ShowHome", "UserAndActivity");
    }

    [HttpGet("activity/{id}")]
    public IActionResult ShowActivity(int id)
    {
      if (HttpContext.Session.GetInt32("UserId") == null)
      {
        return View("Index");
      }

      int? LoggedInUserId = HttpContext.Session.GetInt32("UserId");
      var LoggedInUser = dbContext.Users.FirstOrDefault(u => u.UserId == LoggedInUserId);
      ViewBag.LoggedInUser = LoggedInUser;

      var ActivityToShow = dbContext.Activities.FirstOrDefault(a => a.ActivityId == id);
      ViewBag.ActivityToShow = ActivityToShow;

      var AllActivities = dbContext.Activities
      .Include(uaa => uaa.UserAndActivities)
      .ThenInclude(u => u.User).ToList();

      ViewBag.AllActivities = AllActivities;
      
      return View();
    }
  }
}

Views/Activity/ShowActivity.cshtml
@using beltexam.Models
@model UserAndActivity

@Html.Partial("_HeaderWithHome")

<h2>@ViewBag.ActivityToShow.Title</h2>
<h4 class ="headerspan">Event Coordinator:  @ViewBag.ActivityToShow.CreatorName</h4>

   @if (@ViewBag.ActivityToShow.CreatorId == @ViewBag.LoggedInUser.UserId)
      {
        
          <a class="btn btn-danger" href="/deleteactivity/@ViewBag.ActivityToShow.ActivityId">Delete</a>
        
      }
      else 
      {
        @if (@ViewBag.ActivityToShow.UserAndActivities.Count != 0)
        {
        @foreach (var item in @ViewBag.ActivityToShow.UserAndActivities)
        {
          @if(item.UserId == @ViewBag.LoggedInUser.UserId)
          {
            <td>
              <a class="btn btn-danger" href="/delete/@item.ActivityId">Leave</a>
            </td>
          }
        }
        }
          else
          {
            <td>
              <form asp-action="CreateUserAndActivity" asp-controller="UserAndActivity" method="Post">
                <input type="hidden" asp-for="UserId" value="@ViewBag.LoggedInUser.UserId">
                <input type="hidden" asp-for="ActivityId" value="@ViewBag.ActivityToShow.ActivityId">
                <input type="submit" value="Join" class="btn btn-primary">
              </form>
            </td>
          }
        
      
      
      }
<br>
<h4>Description</h4>
<p>@ViewBag.ActivityToShow.Description</p>

<h4>Participants</h4>
@foreach (var item in @ViewBag.AllActivities)
{
    @foreach (var i in item.UserAndActivities)
    {
        <h4>@i.User.FirstName @i.User.LastName</h4>
    }
}

Views/Activity/ShowCreateActivity.cshtml
@using beltexam.Models
@model Activity
@Html.Partial("_HeaderWithHome")
<h3>Create an activity</h3>

<form asp-controller="Activity" asp-action="CreateActivity" method="post">
  <div>
    <label asp-for="Title"></label>
    <input  asp-for="Title">
    <span asp-validation-for="Title"></span>
    <label class="time" name="Time">Time</label>
    <select name="Hour" type="text">
      <option value="12">12</option>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>
      <option value="9">9</option>
      <option value="10">10</option>
      <option value="11">11</option>
    </select>
    <select name="Minute">
      <option value="00">00</option>
      <option value="15">15</option>
      <option value="30">30</option>
      <option value="45">45</option>
      
    </select>
    <select name="ampm">
      <option value="AM">AM</option>
      <option value="PM">PM</option>
    </select>
    
  </div>
  <div>    
    <label asp-for="Date"></label>
    <input asp-for="Date" type="date">
    <span asp-validation-for="Date"></span>
    <label asp-for="Duration"></label>
    <input asp-for="Duration">
    <span asp-validation-for="Duration"></span>
    <select asp-for="DurationUnit">
      <option value="Minutes">Minutes</option>
      <option value="Hours">Hours</option>
      <option value="Days">Days</option>
    </select>
  </div>
  <label asp-for="Description"></label>
  <br>
  <textarea asp-for="Description" cols="80" rows="6"></textarea>
  <span asp-validation-for="Description"></span>
  <br>
  <input type="hidden" asp-for="CreatorId" value="@ViewBag.LoggedInUserId">
  <input type="hidden" name="FirstName" value="@ViewBag.LoggedInUser.FirstName">
  <input type="hidden" name="LastName" value="@ViewBag.LoggedInUser.LastName">
  <input type="submit" value="Create Activity" class="btn btn-success">

</form>