Models/UserAndActivity.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;
using System.Collections.Generic;

namespace beltexam.Models
{
  public class UserAndActivity
  {
    [Key]
    public int UserAndActivityId { get; set; }
    public int UserId { get; set; }
    public int ActivityId { get; set; }
    public User User { get; set; }
    public Activity Activity { get; set; }
    public UserAndActivity() { }


  }
}

Controllers/UserAndActivityController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using beltexam.Models;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace beltexam.Controllers
{
  public class UserAndActivityController : Controller
  {
    private beltexamContext dbContext;
    
    public UserAndActivityController(beltexamContext context)
    {
      dbContext = context;
      
    }
    [HttpGet("Home")]
    public IActionResult ShowHome()
    {
      if (HttpContext.Session.GetInt32("UserId") == null)
      {
        return View("Index");
      }
      int? LoggedInUserId = HttpContext.Session.GetInt32("UserId");
      var LoggedInUser = dbContext.Users.FirstOrDefault(u => u.UserId == LoggedInUserId);
      ViewBag.LoggedInUser = LoggedInUser;
      var AllActivities = dbContext.Activities
      .Include(uaa => uaa.UserAndActivities)
      .ThenInclude(u => u.User).OrderBy(u => u.Date).ToList();



      ViewBag.AllActivities = AllActivities;
      return View();
    }

    [HttpPost("CreateUserAndActivity")]
    public IActionResult CreateUserAndActivity(UserAndActivity NewUserAndActivity)
    {
      dbContext.Add(NewUserAndActivity);
      dbContext.SaveChanges();
      return RedirectToAction("ShowHome");
    }

    [HttpGet("delete/{id}")]
    public IActionResult DeleteUserAndActivity(int Id)
    {
      var RecordToDelete = dbContext.UsersAndActivities.FirstOrDefault(i => i.ActivityId == Id);
      dbContext.Remove(RecordToDelete);
      dbContext.SaveChanges();
      return RedirectToAction("ShowHome");
    }
  }
}

Views/UserAndActivity/ShowHome.cshtml
@using beltexam.Models
@model UserAndActivity

<h1 class="headerspan">Dojo Activity Center</h1>
<span class="welcome">Welcome @ViewBag.LoggedInUser.FirstName</span><a class="logout" href="/logout">Log Off</a>

<table class="table">
  <thead>
    <tr>
      <th>Activity</th>
      <th>Date and Time</th>
      <th>Duration</th>
      <th>Event Coordinator</th>
      <th>Number of Participants</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  @foreach (var a in @ViewBag.AllActivities)
  {
    @if(@a.Date > DateTime.Now)
    {
    <tr>
      <td><a href="activity/@a.ActivityId">@a.Title</a></td>
      <td>@a.Date</td>
      <td>@a.Duration @a.DurationUnit</td>
      <td>@a.CreatorName</td>
      <td>@a.UserAndActivities.Count</td>

      @if (@a.CreatorId == @ViewBag.LoggedInUser.UserId)
      {
        <td>
          <a class="btn btn-danger" href="/deleteactivity/@a.ActivityId">Delete</a>
        </td>
      }
      else 
      {
        @if (@a.UserAndActivities.Count != 0)
        {
        @foreach (var item in a.UserAndActivities)
        {
          @if(item.UserId == @ViewBag.LoggedInUser.UserId)
          {
            <td>
              <a class="btn btn-danger" href="/delete/@item.ActivityId">Leave</a>
            </td>
          }
        }
        }
          else
          {
            <td>
              <form asp-action="CreateUserAndActivity" asp-controller="UserAndActivity" method="Post">
                <input type="hidden" asp-for="UserId" value="@ViewBag.LoggedInUser.UserId">
                <input type="hidden" asp-for="ActivityId" value="@a.ActivityId">
                <input type="submit" value="Join" class="btn btn-primary">
              </form>
            </td>
          }
        
      
      
      }
      
      
    </tr>
    }
  }
  </tbody>
</table>

<a href="/showcreateactivity" class="createactivity btn btn-primary">Create New Activity </a>